### ISSUE TITLE
Failed prop type: Invalid prop `sx on frontend

### ISSUE THREAD

**Issue by jeffstjean** [UWO-Aero-Design/gnd-station#60]
Running the frontend and opening the console shows the following warning:

```
Warning: Failed prop type: Invalid prop `sx` supplied to `ForwardRef(Grid)`, expected one of type [function, object].
    at Grid (http://localhost:3000/static/js/bundle.js:8850:87)
    at Altimeter (http://localhost:3000/static/js/bundle.js:425:5)
    at li
    at http://localhost:3000/static/js/bundle.js:2051:66
    at ListItem (http://localhost:3000/static/js/bundle.js:11360:83)
    at ul
    at http://localhost:3000/static/js/bundle.js:2051:66
    at List (http://localhost:3000/static/js/bundle.js:11041:82)
    at div
    at http://localhost:3000/static/js/bundle.js:2051:66
    at Grid (http://localhost:3000/static/js/bundle.js:8850:87)
    at div
    at http://localhost:3000/static/js/bundle.js:2051:66
    at Grid (http://localhost:3000/static/js/bundle.js:8850:87)
    at div
    at http://localhost:3000/static/js/bundle.js:2051:66
    at Container (http://localhost:3000/static/js/bundle.js:691
```

**Comment by suresh529** [comment]
In the Grid sx = {{}} use before the container item .

example - < Grid sx ={{ .......}} container item ......>

**Comment by suresh529** [comment]
try this one, I hope your problem is resolve

In the Grid sx = {{}} use before the container item .

example - < Grid sx ={{ .......}} container item ......>
